export const CRM_PIPELINE_LOG = {
  MODULE: 'crm-pipeline',
  ACTIONS: {
    GET_KANBAN: 'CRM_PIPELINE_GET_KANBAN',
    GET_PRODUCT_KANBAN: 'CRM_PIPELINE_GET_PRODUCT_KANBAN',
    GET_TABLE: 'CRM_PIPELINE_GET_TABLE',
  },
  ENTITIES: {
    DEAL: 'CRM_DEAL',
  },
} as const;
