export const BusinessLogActions = {
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_ASSIGNED: 'CUSTOMER_ASSIGNED',
  CUSTOMER_REASSIGNED: 'CUSTOMER_REASSIGNED',
  CUSTOMER_STATUS_CHANGED: 'CUSTOMER_STATUS_CHANGED',
  CUSTOMER_FAIL_RECORDED: 'CUSTOMER_FAIL_RECORDED',
  CUSTOMER_SUCCESS_RECORDED: 'CUSTOMER_SUCCESS_RECORDED',

  TRIAL_STARTED: 'TRIAL_STARTED',
  TRIAL_EXTENDED: 'TRIAL_EXTENDED',
  TRIAL_EXPIRED: 'TRIAL_EXPIRED',
  TRIAL_EXPIRING_ALERT_TRIGGERED: 'TRIAL_EXPIRING_ALERT_TRIGGERED',

  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_EXTENDED: 'SUBSCRIPTION_EXTENDED',
  COMMISSION_RECORDED: 'COMMISSION_RECORDED',

  CUSTOMER_FEEDBACK_ADDED: 'CUSTOMER_FEEDBACK_ADDED',
  CUSTOMER_FEEDBACK_UPDATED: 'CUSTOMER_FEEDBACK_UPDATED',

  LEAD_REASSIGNED_BY_MANAGER: 'LEAD_REASSIGNED_BY_MANAGER',
  LEAD_ESCALATED: 'LEAD_ESCALATED',
  FAIL_REASON_SELECTED: 'FAIL_REASON_SELECTED',
} as const;
