export const LogActions = {
  HTTP_REQUEST: 'HTTP_REQUEST',
  HTTP_EXCEPTION: 'HTTP_EXCEPTION',
  UNHANDLED_EXCEPTION: 'UNHANDLED_EXCEPTION',
  APP_BOOTSTRAP: 'APP_BOOTSTRAP',
  APP_STARTUP: 'APP_STARTUP',
} as const;
