export const ErrorCode = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FORBIDDEN_ACCESS: 'FORBIDDEN_ACCESS',
  ITEM_ALREADY_EXISTS: 'ITEM_ALREADY_EXISTS',
  SYSTEM_ERROR_AUTH: 'SYSTEM_ERROR_AUTH',
  INVALID_TOKEN: 'INVALID_TOKEN',
  FILE_SIZE_EXCEEDS_MAXIMUM_LIMIT: 'FILE_SIZE_EXCEEDS_MAXIMUM_LIMIT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_KEY: 'INVALID_KEY',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  S3_OBJECT_BODY_IS_EMPTY: 'S3_OBJECT_BODY_IS_EMPTY',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',
  CRM_SYNC_JOB_NOT_FOUND: 'CRM_SYNC_JOB_NOT_FOUND',
  CRM_SYNC_CONFIGURATION_ERROR: 'CRM_SYNC_CONFIGURATION_ERROR',
  CRM_SYNC_PROCESSING_FAILED: 'CRM_SYNC_PROCESSING_FAILED',
  CRM_SYNC_REPOSITORY_ERROR: 'CRM_SYNC_REPOSITORY_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
