export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  ITEM_ALREADY_EXISTS = 'ITEM_ALREADY_EXISTS',
  SYSTEM_ERROR_AUTH = 'SYSTEM_ERROR_AUTH',
}